## Q1: Basic NumPy Array

- (a) Reverse the NumPy array:  
  Given: `arr = np.array([1, 2, 3, 6, 4, 5])`

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
reversed = np.flip(arr)

print(reversed)

[5 4 3 2 1]


- (b) Flatten the NumPy array:  
  Given: `array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])`  
  Use any two NumPy in-built methods.

In [3]:
arr1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flat1 = arr1.flatten()
flat2 = arr1.ravel()

print(flat1)
print(flat2)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


- (c) Compare the following NumPy arrays:  
  `arr1 = np.array([[1, 2], [3, 4]])`  
  `arr2 = np.array([[1, 2], [3, 4]])`

In [4]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(np.equal(arr1, arr2))

[[ True  True]
 [ True  True]]


- (d) Find the most frequent value and their indices in the arrays:  
  i. `x = np.array([1,2,3,4,5,1,2,1,1,1])`  
  ii. `y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])`

In [5]:
x = np.array([5,2,3,4,1,1,2,5,1,1])
x1, idx = np.unique(x, return_index=True)
count = np.unique(x, return_counts=True)

print(f"the most frequent element is {x1[0]} and the index of it is {idx[0]}")

the most frequent element is 1 and the index of it is 4


In [6]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
y1, idx1 = np.unique(y, return_index=True)
count1 = np.unique(y, return_counts=True)

print(f"the most frequent element is {y1[0]} and the index of it is {idx1[0]}")

the most frequent element is 1 and the index of it is 0


- (e) For the matrix `gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')`, find:  
  - i. Sum of all elements  
  - ii. Sum of all elements row-wise  
  - iii. Sum of all elements column-wise

In [7]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
total = gfg.sum()
print(total)

rowsum = gfg.sum(axis=1)
print(rowsum)

colsum = gfg.sum(axis=0)
print(colsum)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


- (f) For the matrix `n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])`, find:  
  - i. Sum of diagonal elements  
  - ii. Eigen values of the matrix  
  - iii. Eigen vectors of the matrix  
  - iv. Inverse of the matrix  
  - v. Determinant of the matrix

In [8]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
a = np.diag(n_array) # diagonal vector
sumdia = a.sum()
print(sumdia)

D,V = np.linalg.eig(n_array) # eigen values and eigen vector
print(f"eigen values: {D}")
print(f"eigen vector: {V}")

inverse = np.linalg.inv(n_array) # inverse of matrix
print(f"inverse of the matrix is {inverse}")

determinant  = np.linalg.det(n_array) # determinant of matrix
print(f"determinant of the matrix is {determinant}")

176
eigen values: [98.16835147 28.097044   49.73460452]
eigen vector: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
inverse of the matrix is [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
determinant of the matrix is 137180.0000000001


- (g) Multiply the following matrices and also find the covariance between them:  
  i. `p = [[1, 2], [2, 3]]`, `q = [[4, 5], [6, 7]]`  
  ii. `p = [[1, 2], [2, 3], [4, 5]]`, `q = [[4, 5, 1], [6, 7, 2]]`

In [9]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

product = p@q
print(product)

covar = np.cov(p, q)
print(covar)

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


- (h) For the matrices  
  `x = np.array([[2, 3, 4], [3, 2, 9]])`  
  `y = np.array([[1, 5, 0], [5, 10, 3]])`  
  Find:  
  - Inner product  
  - Outer product  
  - Cartesian product

In [10]:
p = np.array([[2, 3, 4], [3, 2, 9]])
q = np.array([[1, 5, 0], [5, 10, 3]])

innerprod = np.inner(p, q)
print(innerprod)

outerprod = np.outer(p, q)
print(outerprod)

cartesian_product_p, cartesian_product_q = np.meshgrid(p, q)
cartesian_product = np.column_stack((cartesian_product_p.ravel(), cartesian_product_q.ravel()))
print(f"Cartesian product:\n{cartesian_product}")

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
[[ 2  1]
 [ 3  1]
 [ 4  1]
 [ 3  1]
 [ 2  1]
 [ 9  1]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 3  0]
 [ 2  0]
 [ 9  0]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 3 10]
 [ 2 10]
 [ 9 10]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 3  3]
 [ 2  3]
 [ 9  3]]


## Q2: NumPy Mathematics and Statistics

- (a) For the array `array = np.array([[1, -2, 3],[-4, 5, -6]])`, find:  
  - i. Element-wise absolute value  
  - ii. 25th, 50th, and 75th percentile of the array (flattened, per row, per column)  
  - iii. Mean, median, and standard deviation (flattened, per row, per column)

In [16]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
print(f"the absolute array is : \n {np.abs(array)}")

print("flattened percentiles are: ")
flattened_percentiles = np.percentile(array.flatten(), [25, 50, 75])
print(f"the 25th percentile is {flattened_percentiles[0]}")
print(f"the 50th percentile is {flattened_percentiles[1]}")
print(f"the 75th percentile is {flattened_percentiles[2]}")
print("\n")

print("column percentiles are: ")
column_percentiles = np.percentile(array, [25, 50, 75], axis=0)
print(f"the 25th percentile is {column_percentiles[0]}")
print(f"the 50th percentile is {column_percentiles[1]}")
print(f"the 75th percentile is {column_percentiles[2]}")
print("\n")

print("row percentiles are: ")
row_percentiles = np.percentile(array, [25, 50, 75], axis=1)
print(f"the 25th percentile is {row_percentiles[0]}")
print(f"the 50th percentile is {row_percentiles[1]}")
print(f"the 75th percentile is {row_percentiles[2]}")
print("\n")

mean_flattened = np.mean(array)
median_flattened = np.median(array)
std_flattened = np.std(array)

print(f"Mean (flattened): {mean_flattened}")
print(f"Median (flattened): {median_flattened}")
print(f"Standard Deviation (flattened): {std_flattened}")
print("\n")

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

print(f"Mean (columns): {mean_columns}")
print(f"Median (columns): {median_columns}")
print(f"Standard Deviation (columns): {std_columns}")
print("\n")

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

print(f"Mean (rows): {mean_rows}")
print(f"Median (rows): {median_rows}")
print(f"Standard Deviation (rows): {std_rows}")

the absolute array is : 
 [[1 2 3]
 [4 5 6]]
flattened percentiles are: 
the 25th percentile is -3.5
the 50th percentile is -0.5
the 75th percentile is 2.5


column percentiles are: 
the 25th percentile is [-2.75 -0.25 -3.75]
the 50th percentile is [-1.5  1.5 -1.5]
the 75th percentile is [-0.25  3.25  0.75]


row percentiles are: 
the 25th percentile is [-0.5 -5. ]
the 50th percentile is [ 1. -4.]
the 75th percentile is [2.  0.5]


Mean (flattened): -0.5
Median (flattened): -0.5
Standard Deviation (flattened): 3.8622100754188224


Mean (columns): [-1.5  1.5 -1.5]
Median (columns): [-1.5  1.5 -1.5]
Standard Deviation (columns): [2.5 3.5 4.5]


Mean (rows): [ 0.66666667 -1.66666667]
Median (rows): [ 1. -4.]
Standard Deviation (rows): [2.05480467 4.78423336]


- (b) For the array `a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])`, find:  
  - Floor values  
  - Ceiling values  
  - Truncated values  
  - Rounded values

In [18]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
floor_values = np.floor(a)
print(f"Floor values: {floor_values}")

ceil_values = np.ceil(a)
print(f"Ceil values: {ceil_values}")

trunc_values = np.trunc(a)
print(f"Truncated values: {trunc_values}")

rounded_values_default = np.round(a) # Rounds to nearest integer
print(f"Rounded values (default): {rounded_values_default}")

# rounded_values_decimals = np.round(a, decimals=2) # Rounds to 2 decimal places
# print(f"Rounded values (2 decimals): {rounded_values_decimals}")

Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceil values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values (default): [-2. -2. -0.  0.  2.  2.  3.]


## Q3: Searching and Sorting

- (a) For the array `array = np.array([10, 52, 62, 16, 16, 54, 453])`, find:  
  - i. Sorted array  
  - ii. Indices of sorted array  
  - iii. 4 smallest elements  
  - iv. 5 largest elements

In [20]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
sorted_indices = np.argsort(array)
smallest_4 = sorted_array[:4]
largest_5 = sorted_array[-5:]

print(f"Sorted Array: {sorted_array}")
print(f"Indices of Sorted Array: {sorted_indices}")
print(f"4 Smallest Elements: {smallest_4}")
print(f"5 Largest Elements: {largest_5}")


Sorted Array: [ 10  16  16  52  54  62 453]
Indices of Sorted Array: [0 3 4 1 5 2 6]
4 Smallest Elements: [10 16 16 52]
5 Largest Elements: [ 16  52  54  62 453]


- (b) For the array `array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])`, find:  
  - i. Integer elements only  
  - ii. Float elements only

In [23]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integers_only = array[np.mod(array, 1) == 0]
floats_only = array[np.mod(array, 1) != 0]
print(f"Integers Only: {integers_only}")
print(f"Floats Only: {floats_only}")

Integers Only: [1. 2. 3. 2.]
Floats Only: [1.2 2.2]
